### ISSUE TITLE
Error in making Scapi

### ISSUE THREAD

**Issue by marryslsl** [cryptobiu/libscapi#4]
Hi
I have the same problem as previous issue.
Making SCAPI produce these errors
************************
make[1]: Entering directory '/home/me/libscapi/build/OTExtension'
In file included from cbitvector.cpp:8:0:
cbitvector.h:296:16: error: field ‘m_nKey’ has incomplete type ‘EVP_CIPHER_CTX {aka evp_cipher_ctx_st}’
   AES_KEY_CTX  m_nKey;
                ^
In file included from /usr/local/include/openssl/evp.h:14:0,
                 from ../util/typedefs.h:15,
                 from cbitvector.h:18,
                 from cbitvector.cpp:8:
/usr/local/include/openssl/ossl_typ.h:90:16: note: forward declaration of ‘EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}’
 typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
                ^
Makefile:55: recipe for target 'util/*.o' failed
make[1]: *** [util/*.o] Error 1
make[1]: Leaving directory '/home/me/libscapi/build/OTExtension'
makefile:110: recipe for target 'compile-otextension' failed
make: *** [compile-otextension] Error 2
*********************

**Comment by liorbiu** [comment]
As I commented at #3 we are working on converting to support OpenSSL 1.1.0.

**Comment by liorbiu** [comment]
See the instructions [here](https://github.com/cryptobiu/libscapi/issues/3#issuecomment-296654090) for install libscapi with OpenSSL 1.1.0.
